---
- name: "Install bc"
  ansible.builtin.package:
    name: bc
  register: pkg_result
  retries: 12
  delay: 10
  until: pkg_result is success

- name: "Include Ubuntu tasks"
  ansible.builtin.import_tasks: setup-Ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: "Remove default motd"
  become: true
  ansible.builtin.file:
    path: "/etc/motd"
    state: absent

- name: "READHAT | Add motd folder"
  become: true
  ansible.builtin.file:
    path: "/etc/update-motd.d/"
    state: directory
    owner: root
    group: root
    mode: "755"
  when: ansible_os_family == 'RedHat'

- name: "Add scripts on update-motd.d"
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/update-motd.d/{{ item }}"
    owner: root
    group: root
    mode: "755"
  with_items:
    - "{{ motd_to_add }}"

- name: "Remove scripts on update-motd.d"
  become: true
  ansible.builtin.file:
    path: "/etc/update-motd.d/{{ item }}"
    state: absent
  with_items:
    - "{{ motd_to_remove }}"

- name: "REDHAT | Add script on profile"
  ansible.builtin.lineinfile:
    path: /etc/profile
    regexp: "^if [ $UID -gt 199 ]; then /etc/update-motd.d/00-infos; fi"
    line: if [ $UID -gt 199 ]; then /etc/update-motd.d/00-infos; fi
  when: ansible_os_family == 'RedHat'

- name: "REDHAT8+ | remove default /etc/motd.d/*"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/motd.d/cockpit
    - /etc/motd.d/insights-client
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version != '7'
