---
- name: "Include Redhat-7 tasks"
  import_tasks: setup-Redhat-7.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: "Include Ubuntu tasks"
  import_tasks: setup-Ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: 'Configure motd'
  become: true
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '/etc/update-motd.d/{{ item }}'
    owner: root
    group: root
    mode: '755'
  with_items:
    - "{{ motd_to_add }}"

- name: 'Remove motd'
  become: true
  ansible.builtin.file:
    path: '/etc/update-motd.d/{{ item }}'
    state: absent
  with_items:
    - "{{ motd_to_remove }}"
